package br.com.orbe.dao.jdbc;
import br.com.orbe.config.ConnectionFactory;import br.com.orbe.model.*;import java.sql.*;import java.time.*;import java.util.*;
public class ConfiguracaoAgendaDaoJdbc extends AbstractJdbcDao{
 public ConfiguracaoAgendaDaoJdbc(ConnectionFactory f){super(f);} public List<ConfiguracaoAgenda> listar(){List<ConfiguracaoAgenda>x=new ArrayList<>();try(var c=connectionFactory.open();var s=c.prepareStatement("SELECT * FROM configuracao_agenda ORDER BY unidade,dia_semana");var r=s.executeQuery()){while(r.next())x.add(map(r));return x;}catch(SQLException e){throw persistenceException(e);}}
 public ConfiguracaoAgenda salvar(ConfiguracaoAgenda x){String sql="INSERT INTO configuracao_agenda(unidade,dia_semana,hora_abertura,hora_fechamento,intervalo_minutos,ativo) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE hora_abertura=VALUES(hora_abertura),hora_fechamento=VALUES(hora_fechamento),intervalo_minutos=VALUES(intervalo_minutos),ativo=VALUES(ativo)";try(var c=connectionFactory.open();var s=c.prepareStatement(sql)){s.setString(1,x.getUnidade());s.setInt(2,x.getDiaSemana());s.setObject(3,x.getHoraAbertura());s.setObject(4,x.getHoraFechamento());s.setInt(5,x.getIntervaloMinutos());s.setBoolean(6,x.isAtivo());s.executeUpdate();return x;}catch(SQLException e){throw persistenceException(e);}}
 public List<BloqueioAgenda> bloqueios(){List<BloqueioAgenda>x=new ArrayList<>();try(var c=connectionFactory.open();var s=c.prepareStatement("SELECT * FROM bloqueio_agenda WHERE data_bloqueio>=CURRENT_DATE ORDER BY data_bloqueio,hora_inicio");var r=s.executeQuery()){while(r.next()){BloqueioAgenda b=new BloqueioAgenda();b.setId(r.getLong(1));b.setUnidade(r.getString(2));b.setDataBloqueio(r.getObject(3,LocalDate.class));b.setHoraInicio(r.getObject(4,LocalTime.class));b.setHoraFim(r.getObject(5,LocalTime.class));b.setMotivo(r.getString(6));b.setCriadoEm(r.getTimestamp(7).toLocalDateTime());x.add(b);}return x;}catch(SQLException e){throw persistenceException(e);}}
 public BloqueioAgenda salvarBloqueio(BloqueioAgenda b){try(var c=connectionFactory.open();var s=insertStatement(c,"INSERT INTO bloqueio_agenda(unidade,data_bloqueio,hora_inicio,hora_fim,motivo) VALUES(?,?,?,?,?)")){s.setString(1,b.getUnidade());s.setObject(2,b.getDataBloqueio());s.setObject(3,b.getHoraInicio());s.setObject(4,b.getHoraFim());s.setString(5,b.getMotivo());s.executeUpdate();b.setId(generatedId(s));return b;}catch(SQLException e){throw persistenceException(e);}}
 public List<LocalTime> horarios(LocalDate data,String unidade){List<LocalTime>x=new ArrayList<>();String sql="SELECT c.hora_abertura,c.hora_fechamento,c.intervalo_minutos FROM configuracao_agenda c WHERE c.unidade=? AND c.dia_semana=? AND c.ativo=TRUE";try(var c=connectionFactory.open();var s=c.prepareStatement(sql)){s.setString(1,unidade);s.setInt(2,data.getDayOfWeek().getValue());try(var r=s.executeQuery()){if(!r.next())return x;LocalTime atual=r.getObject(1,LocalTime.class),fim=r.getObject(2,LocalTime.class);int intervalo=r.getInt(3);while(atual.isBefore(fim)){x.add(atual);atual=atual.plusMinutes(intervalo);}}try(var s2=c.prepareStatement("SELECT hora_inicio,hora_fim FROM bloqueio_agenda WHERE unidade=? AND data_bloqueio=?")){s2.setString(1,unidade);s2.setObject(2,data);try(var r=s2.executeQuery()){while(r.next()){LocalTime ini=r.getObject(1,LocalTime.class),fim=r.getObject(2,LocalTime.class);x.removeIf(h->ini==null||(!h.isBefore(ini)&&h.isBefore(fim)));}}}try(var s3=c.prepareStatement("SELECT TIME(data_agendamento) FROM agendamento WHERE unidade=? AND DATE(data_agendamento)=? AND status NOT IN('CANCELADO','FALTOU')")){s3.setString(1,unidade);s3.setObject(2,data);try(var r=s3.executeQuery()){while(r.next())x.remove(r.getObject(1,LocalTime.class));}}return x;}catch(SQLException e){throw persistenceException(e);}}
 private ConfiguracaoAgenda map(ResultSet r)throws SQLException{ConfiguracaoAgenda x=new ConfiguracaoAgenda();x.setId(r.getLong("configuracao_agenda_id"));x.setUnidade(r.getString("unidade"));x.setDiaSemana(r.getInt("dia_semana"));x.setHoraAbertura(r.getObject("hora_abertura",LocalTime.class));x.setHoraFechamento(r.getObject("hora_fechamento",LocalTime.class));x.setIntervaloMinutos(r.getInt("intervalo_minutos"));x.setAtivo(r.getBoolean("ativo"));return x;}
}
