package br.com.orbe.dao.jdbc;
import br.com.orbe.config.ConnectionFactory;import br.com.orbe.dto.RelatorioGerencial;import java.sql.*;import java.time.LocalDate;import java.util.*;
public class RelatorioGerencialDaoJdbc extends AbstractJdbcDao{
 public RelatorioGerencialDaoJdbc(ConnectionFactory f){super(f);}public RelatorioGerencial consultar(LocalDate inicio,LocalDate fim){RelatorioGerencial r=new RelatorioGerencial();try(var c=connectionFactory.open()){
  try(var s=c.prepareStatement("SELECT (SELECT COUNT(DISTINCT u.usuario_id) FROM usuario u JOIN usuario_perfil p ON p.usuario_id=u.usuario_id WHERE p.perfil='PACIENTE' AND u.status='ATIVO') pacientes,(SELECT COUNT(*) FROM aplicacao WHERE data_aplicacao>=? AND data_aplicacao<?) aplicacoes,(SELECT COALESCE(SUM(quantidade_atual),0) FROM lote WHERE status='ATIVO' AND data_validade>=CURRENT_DATE) estoque,(SELECT COUNT(*) FROM lote WHERE status='ATIVO' AND (quantidade_atual<=10 OR data_validade<=DATE_ADD(CURRENT_DATE,INTERVAL 60 DAY))) alertas,(SELECT COALESCE(SUM(valor_pago),0) FROM aplicacao WHERE data_aplicacao>=? AND data_aplicacao<?) receita,(SELECT COUNT(*) FROM agendamento WHERE data_agendamento>=? AND data_agendamento<?) total,(SELECT COUNT(*) FROM agendamento WHERE status='CONCLUIDO' AND data_agendamento>=? AND data_agendamento<?) concluidos,(SELECT COUNT(*) FROM agendamento WHERE (status='FALTOU' OR (status IN ('PENDENTE','CONFIRMADO') AND data_agendamento<CURRENT_TIMESTAMP)) AND data_agendamento>=? AND data_agendamento<?) faltas,(SELECT COUNT(*) FROM agendamento WHERE status='CANCELADO' AND data_agendamento>=? AND data_agendamento<?) cancelados,(SELECT COALESCE(SUM(quantidade),0) FROM movimentacao_estoque WHERE tipo IN ('PERDA','VENCIMENTO') AND criado_em>=? AND criado_em<?) perdas")){int i=1;for(int x=0;x<7;x++){s.setObject(i++,inicio.atStartOfDay());s.setObject(i++,fim.plusDays(1).atStartOfDay());}try(var q=s.executeQuery()){q.next();r.setPacientesAtivos(q.getLong("pacientes"));r.setAplicacoesPeriodo(q.getLong("aplicacoes"));r.setDosesEstoque(q.getLong("estoque"));r.setLotesAlerta(q.getLong("alertas"));r.setReceita(q.getBigDecimal("receita"));r.setAgendamentosTotal(q.getLong("total"));r.setConcluidos(q.getLong("concluidos"));r.setFaltas(q.getLong("faltas"));r.setCancelados(q.getLong("cancelados"));r.setDosesPerdidas(q.getLong("perdas"));}}
  listar(c,"SELECT DATE_FORMAT(data_aplicacao,'%x-S%v') periodo,COUNT(*) qtd FROM aplicacao WHERE data_aplicacao>=? AND data_aplicacao<? GROUP BY periodo ORDER BY MIN(data_aplicacao)",(q)->r.getAplicacoesPorSemana().add(new RelatorioGerencial.SerieItem(q.getString(1),q.getLong(2))),inicio.atStartOfDay(),fim.plusDays(1).atStartOfDay());
  listar(c,"SELECT v.nome,COUNT(*) qtd FROM aplicacao a JOIN lote l ON l.lote_id=a.lote_id JOIN vacina v ON v.vacina_id=l.vacina_id WHERE a.data_aplicacao>=? AND a.data_aplicacao<? GROUP BY v.vacina_id,v.nome ORDER BY qtd DESC LIMIT 5",(q)->r.getVacinasMaisAplicadas().add(new RelatorioGerencial.RankingItem(q.getString(1),q.getLong(2))),inicio.atStartOfDay(),fim.plusDays(1).atStartOfDay());
  listar(c,"SELECT u.nome,COUNT(*) qtd FROM aplicacao a JOIN usuario u ON u.usuario_id=a.funcionario_id WHERE a.data_aplicacao>=? AND a.data_aplicacao<? GROUP BY u.usuario_id,u.nome ORDER BY qtd DESC LIMIT 5",(q)->r.getProfissionaisMaisAtivos().add(new RelatorioGerencial.RankingItem(q.getString(1),q.getLong(2))),inicio.atStartOfDay(),fim.plusDays(1).atStartOfDay());
  listar(c,"SELECT l.numero_lote,v.nome,CASE WHEN l.data_validade<=DATE_ADD(CURRENT_DATE,INTERVAL 60 DAY) THEN 'VALIDADE' ELSE 'ESTOQUE' END,l.quantidade_atual,l.data_validade FROM lote l JOIN vacina v ON v.vacina_id=l.vacina_id WHERE l.status='ATIVO' AND (l.quantidade_atual<=10 OR l.data_validade<=DATE_ADD(CURRENT_DATE,INTERVAL 60 DAY)) ORDER BY l.data_validade,l.quantidade_atual LIMIT 5",(q)->r.getAlertas().add(new RelatorioGerencial.AlertaEstoqueItem(q.getString(1),q.getString(2),q.getString(3),q.getLong(4),q.getDate(5).toString())));return r;
 }catch(SQLException e){throw persistenceException(e);}}
 private void listar(Connection c,String sql,RowConsumer consumer,Object...parametros)throws SQLException{try(var s=c.prepareStatement(sql)){for(int i=0;i<parametros.length;i++)s.setObject(i+1,parametros[i]);try(var q=s.executeQuery()){while(q.next())consumer.accept(q);}}}private interface RowConsumer{void accept(ResultSet q)throws SQLException;}
}
