package br.com.orbe.dto;
import java.math.BigDecimal;import java.util.*;
public class RelatorioGerencial {
 private long pacientesAtivos,aplicacoesPeriodo,dosesEstoque,lotesAlerta,agendamentosTotal,concluidos,faltas,cancelados,dosesPerdidas;private BigDecimal receita=BigDecimal.ZERO;private List<SerieItem>aplicacoesPorSemana=new ArrayList<>();private List<RankingItem>vacinasMaisAplicadas=new ArrayList<>(),profissionaisMaisAtivos=new ArrayList<>();private List<AlertaEstoqueItem>alertas=new ArrayList<>();
 public long getPacientesAtivos(){return pacientesAtivos;}public void setPacientesAtivos(long v){pacientesAtivos=v;}public long getAplicacoesPeriodo(){return aplicacoesPeriodo;}public void setAplicacoesPeriodo(long v){aplicacoesPeriodo=v;}public long getDosesEstoque(){return dosesEstoque;}public void setDosesEstoque(long v){dosesEstoque=v;}public long getLotesAlerta(){return lotesAlerta;}public void setLotesAlerta(long v){lotesAlerta=v;}public long getAgendamentosTotal(){return agendamentosTotal;}public void setAgendamentosTotal(long v){agendamentosTotal=v;}public long getConcluidos(){return concluidos;}public void setConcluidos(long v){concluidos=v;}public long getFaltas(){return faltas;}public void setFaltas(long v){faltas=v;}public long getCancelados(){return cancelados;}public void setCancelados(long v){cancelados=v;}public long getDosesPerdidas(){return dosesPerdidas;}public void setDosesPerdidas(long v){dosesPerdidas=v;}public BigDecimal getReceita(){return receita;}public void setReceita(BigDecimal v){receita=v;}public List<SerieItem>getAplicacoesPorSemana(){return aplicacoesPorSemana;}public List<RankingItem>getVacinasMaisAplicadas(){return vacinasMaisAplicadas;}public List<RankingItem>getProfissionaisMaisAtivos(){return profissionaisMaisAtivos;}public List<AlertaEstoqueItem>getAlertas(){return alertas;}
 public static class SerieItem{public String periodo;public long quantidade;public SerieItem(String p,long q){periodo=p;quantidade=q;}public String getPeriodo(){return periodo;}public long getQuantidade(){return quantidade;}}
 public static class RankingItem{public String vacina;public long quantidade;public RankingItem(String v,long q){vacina=v;quantidade=q;}public String getVacina(){return vacina;}public long getQuantidade(){return quantidade;}}
 public static class AlertaEstoqueItem{public String lote,vacina,tipo;public long quantidade;public String validade;public AlertaEstoqueItem(String l,String v,String t,long q,String d){lote=l;vacina=v;tipo=t;quantidade=q;validade=d;}public String getLote(){return lote;}public String getVacina(){return vacina;}public String getTipo(){return tipo;}public long getQuantidade(){return quantidade;}public String getValidade(){return validade;}}
}
