<script lang="ts">
  import Alert from '../../design-system/components/Alert.svelte'; import Button from '../../design-system/components/Button.svelte'; import FormField from '../../design-system/components/FormField.svelte';
  import { authApi } from '../../lib/api';
  let { onBack }: { onBack:()=>void }=$props(); let name=$state('');let cpf=$state('');let email=$state('');let phone=$state('');let birthDate=$state('');let password=$state('');let accepted=$state(false);let error=$state('');let success=$state(false);let loading=$state(false);
  async function submit(e:SubmitEvent){e.preventDefault();error='';if(!name||cpf.replace(/\D/g,'').length!==11||!email.includes('@')||!phone||!birthDate||password.length<8||!accepted){error='Preencha os campos corretamente e aceite os termos para continuar.';return}loading=true;try{await authApi.register({nome:name,cpf,email,telefone:phone,dataNascimento:birthDate,senha:password});success=true}catch(exception){error=exception instanceof Error?exception.message:'Não foi possível realizar o cadastro.'}finally{loading=false}}
</script>
<button class="back" onclick={onBack}>← Voltar ao login</button><div class="heading"><p>Primeiro acesso</p><h2>Crie sua conta</h2><span>Preencha seus dados para começar a cuidar da sua vacinação.</span></div>
{#if success}<div class="success"><Alert tone="success">Cadastro realizado com sucesso. Você já pode entrar com sua nova conta.</Alert><Button fullWidth onclick={onBack}>Ir para o login</Button></div>{:else}<form onsubmit={submit} novalidate>{#if error}<Alert tone="danger">{error}</Alert>{/if}<div class="grid"><FormField id="name" label="Nome completo" placeholder="Seu nome" value={name} oninput={(v)=>name=v} required/><FormField id="cpf" label="CPF" placeholder="000.000.000-00" value={cpf} oninput={(v)=>cpf=v} required/><FormField id="register-email" label="E-mail" type="email" autocomplete="email" placeholder="nome@exemplo.com" value={email} oninput={(v)=>email=v} required/><FormField id="phone" label="Telefone" type="tel" autocomplete="tel" placeholder="(00) 00000-0000" value={phone} oninput={(v)=>phone=v} required/><FormField id="birth-date" label="Data de nascimento" type="date" value={birthDate} oninput={(v)=>birthDate=v} required/></div><FormField id="new-password" label="Senha" type="password" autocomplete="new-password" placeholder="Mínimo de 8 caracteres" value={password} oninput={(v)=>password=v} hint="Use pelo menos 8 caracteres." required/><label class="terms"><input type="checkbox" bind:checked={accepted}/><span>Li e aceito os Termos de Uso e a Política de Privacidade.</span></label><Button type="submit" fullWidth disabled={loading}>{loading?'Criando conta...':'Criar minha conta'}</Button></form>{/if}
<style>.back{margin-bottom:var(--space-6);border:0;background:transparent;padding:0;color:var(--color-brand-500);font-size:var(--text-sm);font-weight:700;cursor:pointer}.heading>p{color:var(--color-brand-500);font-size:var(--text-xs);font-weight:800;letter-spacing:.08em;text-transform:uppercase}.heading h2{margin-top:var(--space-2);font-size:var(--text-2xl);letter-spacing:-.04em}.heading span{display:block;margin-top:var(--space-2);color:var(--text-secondary);font-size:var(--text-sm);line-height:1.5}form,.success{display:grid;gap:var(--space-4);margin-top:var(--space-6)}.grid{display:grid;grid-template-columns:1fr 1fr;gap:var(--space-4)}.terms{display:flex;align-items:flex-start;gap:var(--space-3);color:var(--text-secondary);font-size:var(--text-xs);line-height:1.5}.terms input{width:1rem;height:1rem;margin-top:.1rem;accent-color:var(--color-brand-500)}@media(max-width:500px){.grid{grid-template-columns:1fr}}</style>
