package br.com.orbe.service.impl;
import br.com.orbe.dao.*;import br.com.orbe.dao.jdbc.UsuarioAdministrativoDaoJdbc;import br.com.orbe.dto.UsuarioAdministrativoItem;import br.com.orbe.exception.BusinessException;import br.com.orbe.model.*;import br.com.orbe.model.enums.StatusLote;import br.com.orbe.service.AdministracaoService;import java.time.LocalDate;import java.util.List;
public class AdministracaoServiceImpl implements AdministracaoService {
 private final UsuarioAdministrativoDaoJdbc u;private final LoteDao l;private final ConvenioDao c;private final MovimentacaoEstoqueDao m;private final AuditoriaDao a;private final br.com.orbe.dao.jdbc.RelatorioGerencialDaoJdbc r;
 public AdministracaoServiceImpl(UsuarioAdministrativoDaoJdbc u,LoteDao l,ConvenioDao c,MovimentacaoEstoqueDao m,AuditoriaDao a,br.com.orbe.dao.jdbc.RelatorioGerencialDaoJdbc r){this.u=u;this.l=l;this.c=c;this.m=m;this.a=a;this.r=r;}
 public List<UsuarioAdministrativoItem> listarUsuarios(){return u.listar();}public List<Lote> listarLotes(){return l.listarTodos();}
 public Lote salvarLote(Lote x){if(x.getVacinaId()==null||x.getNumeroLote()==null||x.getNumeroLote().isBlank())throw new BusinessException("Vacina e lote são obrigatórios.");if(x.getDataValidade()==null||x.getDataValidade().isBefore(LocalDate.now()))throw new BusinessException("A validade deve ser futura.");if(x.getQuantidadeInicial()<=0)throw new BusinessException("A quantidade deve ser positiva.");if(x.getId()==null){x.setQuantidadeAtual(x.getQuantidadeInicial());if(x.getStatus()==null)x.setStatus(StatusLote.ATIVO);return l.salvar(x);}return l.atualizar(x);}
 public List<Convenio> listarConvenios(){return c.listarTodos();}public Convenio salvarConvenio(Convenio x){if(x.getNome()==null||x.getNome().isBlank()||x.getPlano()==null||x.getPlano().isBlank()||x.getCodigoOperacional()==null||x.getCodigoOperacional().isBlank()||x.getTipoCobertura()==null)throw new BusinessException("Convênio, plano, código e cobertura são obrigatórios.");if(x.getTipoCobertura()==br.com.orbe.model.enums.TipoCobertura.PERCENTUAL&&(x.getPercentualDesconto()==null||x.getPercentualDesconto().signum()<0||x.getPercentualDesconto().compareTo(java.math.BigDecimal.valueOf(100))>0))throw new BusinessException("Informe um percentual entre 0 e 100.");if(x.getTipoCobertura()==br.com.orbe.model.enums.TipoCobertura.COPARTICIPACAO&&(x.getValorCoparticipacao()==null||x.getValorCoparticipacao().signum()<0))throw new BusinessException("Informe o valor da coparticipação.");return x.getId()==null?c.salvar(x):c.atualizar(x);}
 public List<MovimentacaoEstoque> listarMovimentacoes(){return m.listarTodos();}public List<Auditoria> listarAuditoria(){return a.listarTodos();}
 public br.com.orbe.dto.RelatorioGerencial relatorio(LocalDate inicio,LocalDate fim){if(inicio==null||fim==null||fim.isBefore(inicio))throw new BusinessException("Período inválido.");return r.consultar(inicio,fim);}
}
