package br.com.orbe.servlet;
import br.com.orbe.config.ApplicationContextListener;import br.com.orbe.dto.ApiResponse;import br.com.orbe.model.*;import br.com.orbe.service.AdministracaoService;import br.com.orbe.util.JsonUtil;import jakarta.servlet.ServletException;import jakarta.servlet.annotation.WebServlet;import jakarta.servlet.http.*;import java.io.IOException;
@WebServlet("/api/admin/*") public class AdministracaoServlet extends BaseServlet {
 private AdministracaoService service;public void init()throws ServletException{service=(AdministracaoService)getServletContext().getAttribute(ApplicationContextListener.ADMINISTRACAO_SERVICE);}
 protected void doGet(HttpServletRequest q,HttpServletResponse s)throws IOException{try{Object d=switch(recurso(q)){case"usuarios"->service.listarUsuarios();case"lotes"->service.listarLotes();case"convenios"->service.listarConvenios();case"movimentacoes"->service.listarMovimentacoes();case"auditoria"->service.listarAuditoria();case"relatorio"->service.relatorio(java.time.LocalDate.parse(q.getParameter("inicio")),java.time.LocalDate.parse(q.getParameter("fim")));default->throw new IllegalArgumentException("Recurso inválido.");};json(s,200,ApiResponse.ok(d));}catch(Exception e){handleException(s,e);}}
 protected void doPost(HttpServletRequest q,HttpServletResponse s)throws IOException{salvar(q,s,false);}protected void doPut(HttpServletRequest q,HttpServletResponse s)throws IOException{salvar(q,s,true);}
 private void salvar(HttpServletRequest q,HttpServletResponse s,boolean edit)throws IOException{try{Object result;if("lotes".equals(recurso(q))){Lote x=JsonUtil.mapper().readValue(q.getReader(),Lote.class);if(edit)x.setId(id(q));result=service.salvarLote(x);}else if("convenios".equals(recurso(q))){Convenio x=JsonUtil.mapper().readValue(q.getReader(),Convenio.class);if(edit)x.setId(id(q));result=service.salvarConvenio(x);}else throw new IllegalArgumentException("Operação inválida.");json(s,edit?200:201,edit?ApiResponse.ok(result):ApiResponse.criado("Registro cadastrado.",result));}catch(Exception e){handleException(s,e);}}
 private String recurso(HttpServletRequest q){String[]x=q.getPathInfo()==null?new String[0]:q.getPathInfo().substring(1).split("/");return x.length==0?"":x[0];}private Long id(HttpServletRequest q){String[]x=q.getPathInfo().substring(1).split("/");if(x.length<2)throw new IllegalArgumentException("Identificador obrigatório.");return Long.valueOf(x[1]);}
}
